# Numpy Basics

In [1]:
import numpy as np

## Arrays

In [2]:
arr = [1,2,3]

In [3]:
arr = np.array(arr)

In [4]:
arr

array([1, 2, 3])

In [5]:
type(arr)

numpy.ndarray

## Matrix

In [6]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
matrix = np.array(matrix)

In [8]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
type(matrix)

numpy.ndarray

## Size

In [10]:
arr.size

3

In [11]:
matrix.size

9

## Shape

In [12]:
arr.shape

(3,)

In [13]:
matrix.shape

(3, 3)

In [14]:
np.shape(matrix)

(3, 3)

## Reshaping Arrays
note: must still have m*n number of elements

In [15]:
numbers = [1,2,3,4,5,6]

In [16]:
arr1 = np.array(numbers)

In [17]:
arr1

array([1, 2, 3, 4, 5, 6])

In [18]:
arr1.shape

(6,)

In [19]:
arr2 = np.reshape(arr1,(3,2))

In [20]:
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
arr2.shape

(3, 2)

# Flatten an Array
i.e. reduce it to one dimension

In [22]:
big_arr = np.arange(0,25).reshape((5,5))
big_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
big_arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
big_arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## Generate a Range of Numbers

In [25]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## Find Max and Min

In [27]:
values = [1,5,8,11,90]
values = np.array(values)
values

array([ 1,  5,  8, 11, 90])

In [28]:
values.max()

90

In [29]:
np.max(values)

90

In [30]:
values.min()

1

In [31]:
values2 = [[1,5,8],[11,90,1111]]
values2 = np.array(values2)
values2

array([[   1,    5,    8],
       [  11,   90, 1111]])

In [32]:
values2.max()

1111

In [33]:
values2.min()

1

## Find Location of Max and Min
below gives you the index of the max/min value

In [34]:
values.argmax()

4

In [35]:
values2.argmax()

5

## Generate an Array of Zeros

In [36]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
np.zeros((3,4)) #3 rows, 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Generate an Array of Ones

In [39]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [40]:
np.ones((5,2)) #5 rows, 2 columsn

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

## Create an Array of Linearly Spaced Numbers

In [41]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [42]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [43]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [44]:
np.shape(np.linspace(0,10,20))

(20,)

## Create an Identity Matrix 
i.e. square matrix, with mostly 0s, but with 1s across the diagonal 

In [45]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Generate Random Numbers from a Uniform Distribution

In [46]:
np.random.seed(0)
np.random.rand(1)

array([0.5488135])

In [47]:
np.random.seed(0)
np.random.rand(6)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411])

In [48]:
np.random.seed(0)
arr3 = np.random.rand(6)
arr3 = np.reshape(arr3,(3,2))
arr3

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411]])

In [49]:
np.random.seed(0)
np.random.rand(3,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411]])

## Generate Random Integer from a Uniform Distribution

In [50]:
np.random.seed(0)
np.random.randint(1,100)

45

In [51]:
np.random.seed(0)
np.random.randint(1,100,size=(3,))

array([45, 48, 65])

## Generate Random Numbers from a Standard Distribution

In [52]:
np.random.seed(0)
np.random.randn(3,2)

array([[ 1.76405235,  0.40015721],
       [ 0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788]])

## Generate Random Numbers from a LogNormal Distribution

In [53]:
np.random.seed(0)
np.random.lognormal(mean=0.0,sigma=1.0,size=(3,))

array([5.83603919, 1.49205924, 2.66109578])

In [54]:
np.random.seed(0)
np.random.lognormal(mean=10.0,sigma=1.0,size=(3,))

array([128547.31761031,  32864.79188862,  58614.53510282])

In [55]:
np.random.seed(0)
np.random.lognormal(mean=0.0,sigma=10.0,size=(3,))

array([4.58333917e+07, 5.46840504e+01, 1.78075863e+04])

## Generate Random Numbers from a Weibull Distribution

In [56]:
np.random.seed(0)
np.random.weibull(4,size=(3,)) #input 'a' is shape parameter

array([0.94451998, 1.05862324, 0.98022702])

In [57]:
np.random.seed(0)
np.random.weibull(4,size=(3,3)) 

array([[0.94451998, 1.05862324, 0.98022702],
       [0.94193608, 0.86158366, 1.00940627],
       [0.87099358, 1.22112599, 1.34932947]])